[package]
name = "log-archiver"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
sqlx = { version = "0.5", default_features = false, features = ["macros", "postgres", "json", "runtime-actix-rustls"] }
dotenv = "0.15"
main_error = "0.1"
tokio = { version = "1", features = ["macros", "time"] }
reqwest = { version = "0.11", default-features = false , features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }